#!/usr/bin/perl -w

use strict;
use Data::Dumper;

require Lexer;
require Parser;
require Compiler;

my @data = <>;
my $data = join '', @data;

my $token_ref = Lexer::lex($data);
my $tree_ref = Parser::parse($token_ref);
Compiler::compile($tree_ref);
